# docker-compose.yml

services:
  backend:
    build: ./job-platform/backend
    ports:
      - "5000:5000"
    env_file:
      - ./job-platform/backend/.env  # Updated path
    volumes:
      - ./job-platform/backend:/app
    networks:
      - job-network

  frontend:
    build: ./job-platform/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./job-platform/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000
      - REACT_APP_SUPABASE_URL=https://dhnveaaocdgibcxgbsaj.supabase.co
      - REACT_APP_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRobnZlYWFvY2RnaWJjeGdic2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTkyOTIsImV4cCI6MjA2MzQ3NTI5Mn0.mqq-3e9oZQVDp5rDwrCfK3mnByR22XMrfMICVRYuhQM  
    depends_on:
      - backend
    networks:
      - job-network

networks:
  job-network:
    driver: bridge